name: Azure CD Pipeline

on:
  push:
    branches:
      - master  # Runs on pushes to the main branch
  pull_request:
    branches:
      - master  # Runs on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Install Dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApplicationWinukka'  
        slot-name: 'production'  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set in your repo secrets
        package: '.WebApplication/bin/Release/net8.0'  # Path to your web app project or web deploy package


